In [1]:
#ebay_car_price_exploration_with_logistic_regression_v001.ipynb

In [2]:
import numpy as np
import pandas as pd
import statsmodels
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset_location = 'https://firebasestorage.googleapis.com/v0/b/acst001.appspot.com/o/Dataset_eBay_Toyota_Corolla_v001.csv?alt=media&token=0d7c808c-823b-4eb8-ae94-9a279c5d98c4'

toyota_corolla_df = pd.read_csv(dataset_location)

# For a dataset in the working directory, it's possible to use the following command:
# toyota_corolla_df = pd.read_csv('Dataset_eBay_Toyota_Corolla_v001.csv')

In [4]:
toyota_corolla_df.head(2)

   record_id  kilometers     miles  price_usd    year   maker    model
0        736       25999   16155.0    13100.0  2006.0  Toyota  Corolla
1        845      321869  200000.0      325.0  1991.0  Toyota  Corolla

In [5]:
toyota_corolla_df.tail(2)

     record_id  kilometers     miles  price_usd    year   maker    model
831     146385      106469   66157.0     4299.0  2001.0  Toyota  Corolla
832     146673      257495  160000.0      560.0  1995.0  Toyota  Corolla

In [6]:
toyota_corolla_df.sample(5)

     record_id  kilometers     miles  price_usd    year   maker    model
359      63093      205996  128000.0    3401.03  1997.0  Toyota  Corolla
785     139136       56890   35350.0    7899.00  2001.0  Toyota  Corolla
344      62206       59546   37000.0    7311.00  2004.0  Toyota  Corolla
664     117031      265220  164800.0    1925.00  1997.0  Toyota  Corolla
656     116001      279434  173632.0     255.00  1994.0  Toyota  Corolla

In [7]:
toyota_corolla_df.describe()

           record_id     kilometers          miles     price_usd         year
count     833.000000     833.000000     833.000000    833.000000   833.000000
mean    74156.343337  172716.007203  107320.762305   4236.381885  1995.776711
std     42072.439847  109435.855132   68000.294588   3833.479195     7.219471
min       736.000000     161.000000     100.000000     50.000000  1969.000000
25%     37385.000000   82881.000000   51500.000000   1200.000000  1991.000000
50%     74805.000000  169786.000000  105500.000000   2749.980000  1996.000000
75%    111422.000000  252667.000000  157000.000000   7000.000000  2002.000000
max    146673.000000  600990.000000  373438.000000  16505.000000  2006.000000

# Regressions without indicator variables

In [8]:
print('Regressing the price on the number of kilometers driven:\n')
results_ols = smf.ols('price_usd ~ kilometers', 
               data=toyota_corolla_df
               ).fit(cov_type='HC0')
print(' ')
print('coefficient of kilometers - mean:\n',
      results_ols.params['kilometers'])
print('coefficient of kilometers - confidence interval:\n',
      results_ols.conf_int()[0]['kilometers'], 
      results_ols.conf_int()[1]['kilometers'])
print(' ')
results_ols.summary()

Regressing the price on the number of kilometers driven:


coefficient of kilometers - mean:
 -0.026112883668289524
coefficient of kilometers - confidence interval:
 -0.028134697158200973 -0.024091070178378075

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              price_usd   R-squared:                       0.556
Model:                            OLS   Adj. R-squared:                  0.555
Method:                 Least Squares   F-statistic:                     640.8
Date:                Mon, 15 Aug 2022   Prob (F-statistic):          2.98e-105
Time:                        21:14:02   Log-Likelihood:                -7717.1
No. Observations:                 833   AIC:                         1.544e+04
Df Residuals:                     831   BIC:                         1.545e+04
Df Model:                           1
Covariance Type:                  HC0
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   8746.4949    221.922     39.413      0.000    8311.537    9181.453
kilometers    -0.0261      0.001    -25.314      0.000      -0.028      -0.024
==============================================================================
Omnibus:                       19.474   Durbin-Watson:                   1.683
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               20.503
Skew:                           0.349   Prob(JB):                     3.53e-05
Kurtosis:                       3.322   Cond. No.                     3.82e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC0)
[2] The condition number is large, 3.82e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [9]:
print('Regressing the price on the number of kilometers driven and the model year:\n')
results_ols = smf.ols('price_usd ~ kilometers + year', 
               data=toyota_corolla_df
               ).fit(cov_type='HC0')
print(' ')
print('coefficient of kilometers - mean:\n',
      results_ols.params['kilometers'])
print('coefficient of kilometers - confidence interval:\n',
      results_ols.conf_int()[0]['kilometers'], 
      results_ols.conf_int()[1]['kilometers'])
print(' ')
results_ols.summary()

Regressing the price on the number of kilometers driven and the model year:


coefficient of kilometers - mean:
 -0.017459071201082383
coefficient of kilometers - confidence interval:
 -0.019459952823817333 -0.015458189578347433

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              price_usd   R-squared:                       0.695
Model:                            OLS   Adj. R-squared:                  0.694
Method:                 Least Squares   F-statistic:                     543.7
Date:                Mon, 15 Aug 2022   Prob (F-statistic):          1.24e-151
Time:                        21:14:03   Log-Likelihood:                -7561.1
No. Observations:                 833   AIC:                         1.513e+04
Df Residuals:                     830   BIC:                         1.514e+04
Df Model:                           2
Covariance Type:                  HC0
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -4.665e+05   3.22e+04    -14.483      0.000    -5.3e+05   -4.03e+05
kilometers    -0.0175      0.001    -17.102      0.000      -0.019      -0.015
year         237.3825     16.088     14.755      0.000     205.851     268.914
==============================================================================
Omnibus:                       97.580   Durbin-Watson:                   1.689
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              142.743
Skew:                           0.833   Prob(JB):                     1.01e-31
Kurtosis:                       4.156   Cond. No.                     6.81e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC0)
[2] The condition number is large, 6.81e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [10]:
print('Regressing the price on the number of kilometers driven for model year 2000:\n')
results_ols = smf.ols('price_usd ~ kilometers', 
               data=toyota_corolla_df[toyota_corolla_df['year']==2000]
               ).fit(cov_type='HC0')
print(' ')
print('coefficient of kilometers - mean:\n',
      results_ols.params['kilometers'])
print('coefficient of kilometers - confidence interval:\n',
      results_ols.conf_int()[0]['kilometers'], 
      results_ols.conf_int()[1]['kilometers'])
print(' ')
results_ols.summary()

Regressing the price on the number of kilometers driven for model year 2000:


coefficient of kilometers - mean:
 -0.01826702781763866
coefficient of kilometers - confidence interval:
 -0.026443240199669003 -0.010090815435608318

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              price_usd   R-squared:                       0.325
Model:                            OLS   Adj. R-squared:                  0.299
Method:                 Least Squares   F-statistic:                     19.17
Date:                Mon, 15 Aug 2022   Prob (F-statistic):           0.000173
Time:                        21:14:03   Log-Likelihood:                -240.87
No. Observations:                  28   AIC:                             485.7
Df Residuals:                      26   BIC:                             488.4
Df Model:                           1
Covariance Type:                  HC0
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   6621.9338    747.435      8.860      0.000    5156.988    8086.880
kilometers    -0.0183      0.004     -4.379      0.000      -0.026      -0.010
==============================================================================
Omnibus:                        6.438   Durbin-Watson:                   1.469
Prob(Omnibus):                  0.040   Jarque-Bera (JB):                5.085
Skew:                          -1.030   Prob(JB):                       0.0787
Kurtosis:                       3.336   Cond. No.                     4.13e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC0)
[2] The condition number is large, 4.13e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [11]:
print('Regressing the price on the number of kilometers driven for model year 2005:\n')
results_ols = smf.ols('price_usd ~ kilometers', 
               data=toyota_corolla_df[toyota_corolla_df['year']==2005]
               ).fit(cov_type='HC0')
print(' ')
print('coefficient of kilometers - mean:\n',
      results_ols.params['kilometers'])
print('coefficient of kilometers - confidence interval:\n',
      results_ols.conf_int()[0]['kilometers'], 
      results_ols.conf_int()[1]['kilometers'])
print(' ')
results_ols.summary()

Regressing the price on the number of kilometers driven for model year 2005:


coefficient of kilometers - mean:
 0.03043441541948763
coefficient of kilometers - confidence interval:
 -0.004008161204910696 0.06487699204388596

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              price_usd   R-squared:                       0.034
Model:                            OLS   Adj. R-squared:                  0.019
Method:                 Least Squares   F-statistic:                     2.999
Date:                Mon, 15 Aug 2022   Prob (F-statistic):             0.0882
Time:                        21:14:03   Log-Likelihood:                -600.70
No. Observations:                  65   AIC:                             1205.
Df Residuals:                      63   BIC:                             1210.
Df Model:                           1
Covariance Type:                  HC0
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   9538.4403    666.318     14.315      0.000    8232.481    1.08e+04
kilometers     0.0304      0.018      1.732      0.083      -0.004       0.065
==============================================================================
Omnibus:                        6.515   Durbin-Watson:                   0.936
Prob(Omnibus):                  0.038   Jarque-Bera (JB):                6.079
Skew:                          -0.744   Prob(JB):                       0.0479
Kurtosis:                       3.173   Cond. No.                     7.16e+04
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC0)
[2] The condition number is large, 7.16e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Regressions with fixed effects

In [12]:
# Regression with year fixed effects

results_ols = smf.ols('price_usd ~ kilometers + C(year)', 
               data=toyota_corolla_df
               ).fit(cov_type='HC0')
print('')
print('Regression with year fixed effects')
print('')
print('coefficient of kilometers:\n',
      results_ols.params['kilometers'])
results_ols.summary()

Regression with year fixed effects

coefficient of kilometers:
 -0.006791604874303556

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              price_usd   R-squared:                       0.857
Model:                            OLS   Adj. R-squared:                  0.850
Method:                 Least Squares   F-statistic:                     108.8
Date:                Mon, 15 Aug 2022   Prob (F-statistic):          3.95e-269
Time:                        21:14:03   Log-Likelihood:                -7246.4
No. Observations:                 833   AIC:                         1.457e+04
Df Residuals:                     795   BIC:                         1.475e+04
Df Model:                          37
Covariance Type:                  HC0
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          7162.4419      8.329    859.974      0.000    7146.118    7178.766
C(year)[T.1970.0] -3000.5037     26.145   -114.763      0.000   -3051.747   -2949.260
C(year)[T.1971.0] -3478.8217   1595.888     -2.180      0.029   -6606.705    -350.938
C(year)[T.1972.0] -4040.8189     27.068   -149.286      0.000   -4093.871   -3987.767
C(year)[T.1974.0] -3940.6697    704.278     -5.595      0.000   -5321.030   -2560.309
C(year)[T.1975.0] -3945.7101     55.176    -71.511      0.000   -4053.854   -3837.567
C(year)[T.1976.0]  -799.2842   2509.293     -0.319      0.750   -5717.408    4118.839
C(year)[T.1977.0] -3248.5093   1063.040     -3.056      0.002   -5332.030   -1164.989
C(year)[T.1978.0] -4666.1173    782.474     -5.963      0.000   -6199.738   -3132.496
C(year)[T.1979.0] -4829.7714    332.946    -14.506      0.000   -5482.333   -4177.209
C(year)[T.1980.0] -4529.7456    424.851    -10.662      0.000   -5362.437   -3697.054
C(year)[T.1981.0] -4896.7496    423.062    -11.575      0.000   -5725.936   -4067.563
C(year)[T.1982.0] -3253.4347    303.990    -10.702      0.000   -3849.245   -2657.624
C(year)[T.1983.0] -3598.4838    538.599     -6.681      0.000   -4654.119   -2542.848
C(year)[T.1984.0] -3526.6695    648.694     -5.437      0.000   -4798.087   -2255.252
C(year)[T.1985.0] -3293.7342    336.339     -9.793      0.000   -3952.947   -2634.521
C(year)[T.1986.0] -3390.5328    601.840     -5.634      0.000   -4570.117   -2210.949
C(year)[T.1987.0] -4310.0579    253.359    -17.012      0.000   -4806.632   -3813.483
C(year)[T.1988.0] -4239.5168    334.168    -12.687      0.000   -4894.475   -3584.559
C(year)[T.1989.0] -4235.7606    223.059    -18.989      0.000   -4672.948   -3798.574
C(year)[T.1990.0] -4627.4251    192.639    -24.021      0.000   -5004.990   -4249.860
C(year)[T.1991.0] -4260.5336    234.340    -18.181      0.000   -4719.831   -3801.236
C(year)[T.1992.0] -4520.3704    173.761    -26.015      0.000   -4860.935   -4179.806
C(year)[T.1993.0] -3842.6396    195.657    -19.640      0.000   -4226.120   -3459.159
C(year)[T.1994.0] -3908.4896    185.328    -21.090      0.000   -4271.725   -3545.254
C(year)[T.1995.0] -3677.6167    177.029    -20.774      0.000   -4024.587   -3330.647
C(year)[T.1996.0] -3608.2079    231.721    -15.571      0.000   -4062.372   -3154.044
C(year)[T.1997.0] -3147.3238    181.519    -17.339      0.000   -3503.094   -2791.553
C(year)[T.1998.0] -2551.9919    234.605    -10.878      0.000   -3011.809   -2092.175
C(year)[T.1999.0] -2188.2209    212.361    -10.304      0.000   -2604.442   -1772.000
C(year)[T.2000.0] -2086.7738    289.264     -7.214      0.000   -2653.721   -1519.827
C(year)[T.2001.0]  -970.5196    267.330     -3.630      0.000   -1494.478    -446.562
C(year)[T.2002.0]   -53.3254    323.496     -0.165      0.869    -687.366     580.716
C(year)[T.2003.0]  2220.3774    198.668     11.176      0.000    1830.996    2609.759
C(year)[T.2004.0]  2639.9104    306.016      8.627      0.000    2040.130    3239.691
C(year)[T.2005.0]  3473.2136    318.071     10.920      0.000    2849.806    4096.621
C(year)[T.2006.0]  4974.9948    439.615     11.317      0.000    4113.366    5836.624
kilometers           -0.0068      0.001    -10.499      0.000      -0.008      -0.006
==============================================================================
Omnibus:                       72.339   Durbin-Watson:                   1.621
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              407.451
Skew:                           0.028   Prob(JB):                     3.34e-89
Kurtosis:                       6.426   Cond. No.                     3.61e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC0)
[2] The condition number is large, 3.61e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Regressions with interactions of indicator variables

In [13]:
# Regression with interactions between kilometers and year indicators

results_ols = smf.ols('price_usd ~ kilometers*C(year)', 
               data=toyota_corolla_df
               ).fit(cov_type='HC0')
print('')
print('Regression with interactions between kilometers and year indicators')
results_ols.summary()

Regression with interactions between kilometers and year indicators

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              price_usd   R-squared:                       0.872
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                 5.599e+15
Date:                Mon, 15 Aug 2022   Prob (F-statistic):               0.00
Time:                        21:14:03   Log-Likelihood:                -7198.2
No. Observations:                 833   AIC:                         1.453e+04
Df Residuals:                     764   BIC:                         1.486e+04
Df Model:                          68
Covariance Type:                  HC0
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                     1586.7928    108.040     14.687      0.000    1375.038    1798.548
C(year)[T.1970.0]            -7.685e-06   1.52e-07    -50.692      0.000   -7.98e-06   -7.39e-06
C(year)[T.1971.0]             5825.9822    108.040     53.924      0.000    5614.227    6037.737
C(year)[T.1972.0]            -4.952e-06   1.48e-07    -33.402      0.000   -5.24e-06   -4.66e-06
C(year)[T.1974.0]             -748.3216    759.792     -0.985      0.325   -2237.487     740.844
C(year)[T.1975.0]            -6.152e-06   8.16e-08    -75.398      0.000   -6.31e-06   -5.99e-06
C(year)[T.1976.0]             8353.8206    108.040     77.321      0.000    8142.066    8565.575
C(year)[T.1977.0]            -2735.3762    108.040    -25.318      0.000   -2947.131   -2523.621
C(year)[T.1978.0]             -476.1269    904.653     -0.526      0.599   -2249.215    1296.961
C(year)[T.1979.0]              541.2391    800.294      0.676      0.499   -1027.308    2109.786
C(year)[T.1980.0]              197.4245    138.412      1.426      0.154     -73.859     468.708
C(year)[T.1981.0]            -8.843e+04    108.040   -818.478      0.000   -8.86e+04   -8.82e+04
C(year)[T.1982.0]            -4.509e-06   3.46e-08   -130.513      0.000   -4.58e-06   -4.44e-06
C(year)[T.1983.0]             3117.4177    204.659     15.232      0.000    2716.294    3518.542
C(year)[T.1984.0]             -511.0931   1282.828     -0.398      0.690   -3025.390    2003.203
C(year)[T.1985.0]               65.4216    499.189      0.131      0.896    -912.971    1043.814
C(year)[T.1986.0]             1614.3273   1177.500      1.371      0.170    -693.531    3922.186
C(year)[T.1987.0]              220.7327    472.560      0.467      0.640    -705.467    1146.933
C(year)[T.1988.0]             -918.5330    409.087     -2.245      0.025   -1720.330    -116.736
C(year)[T.1989.0]             1062.8597    434.811      2.444      0.015     210.646    1915.073
C(year)[T.1990.0]              -11.3606    352.931     -0.032      0.974    -703.092     680.371
C(year)[T.1991.0]             1598.2903    591.489      2.702      0.007     438.992    2757.588
C(year)[T.1992.0]              544.6490    367.340      1.483      0.138    -175.325    1264.622
C(year)[T.1993.0]             2058.4739    480.473      4.284      0.000    1116.763    3000.184
C(year)[T.1994.0]             2552.5543    409.971      6.226      0.000    1749.025    3356.083
C(year)[T.1995.0]             1947.4925    474.069      4.108      0.000    1018.334    2876.651
C(year)[T.1996.0]             1439.5151    904.150      1.592      0.111    -332.586    3211.616
C(year)[T.1997.0]             3481.4458    455.894      7.637      0.000    2587.911    4374.981
C(year)[T.1998.0]             3952.9141    603.591      6.549      0.000    2769.897    5135.931
C(year)[T.1999.0]             4383.7075    737.223      5.946      0.000    2938.777    5828.638
C(year)[T.2000.0]             5035.1410    732.444      6.874      0.000    3599.578    6470.704
C(year)[T.2001.0]             5871.3088    527.675     11.127      0.000    4837.085    6905.532
C(year)[T.2002.0]             6435.0136    928.559      6.930      0.000    4615.071    8254.956
C(year)[T.2003.0]             8341.9780    440.962     18.918      0.000    7477.708    9206.248
C(year)[T.2004.0]             9055.8543    561.013     16.142      0.000    7956.290    1.02e+04
C(year)[T.2005.0]             7951.6475    654.786     12.144      0.000    6668.291    9235.004
C(year)[T.2006.0]             9766.8757    726.966     13.435      0.000    8342.048    1.12e+04
kilometers                       0.4263      0.008     50.798      0.000       0.410       0.443
kilometers:C(year)[T.1970.0]    -0.3847      0.006    -60.454      0.000      -0.397      -0.372
kilometers:C(year)[T.1971.0]    -0.4748      0.008    -56.587      0.000      -0.491      -0.458
kilometers:C(year)[T.1972.0]    -0.4050      0.006    -63.115      0.000      -0.418      -0.392
kilometers:C(year)[T.1974.0]    -0.4200      0.008    -50.725      0.000      -0.436      -0.404
kilometers:C(year)[T.1975.0]    -0.4165      0.007    -57.120      0.000      -0.431      -0.402
kilometers:C(year)[T.1976.0]    -0.4613      0.008    -54.967      0.000      -0.478      -0.445
kilometers:C(year)[T.1977.0]    -0.4171      0.008    -49.711      0.000      -0.434      -0.401
kilometers:C(year)[T.1978.0]    -0.4199      0.009    -44.468      0.000      -0.438      -0.401
kilometers:C(year)[T.1979.0]    -0.4314      0.009    -50.055      0.000      -0.448      -0.414
kilometers:C(year)[T.1980.0]    -0.4288      0.008    -51.116      0.000      -0.445      -0.412
kilometers:C(year)[T.1981.0]     0.3003      0.008     35.786      0.000       0.284       0.317
kilometers:C(year)[T.1982.0]    -0.4283      0.008    -52.432      0.000      -0.444      -0.412
kilometers:C(year)[T.1983.0]    -0.4407      0.008    -51.955      0.000      -0.457      -0.424
kilometers:C(year)[T.1984.0]    -0.4241      0.008    -50.714      0.000      -0.440      -0.408
kilometers:C(year)[T.1985.0]    -0.4238      0.008    -50.362      0.000      -0.440      -0.407
kilometers:C(year)[T.1986.0]    -0.4309      0.008    -53.995      0.000      -0.446      -0.415
kilometers:C(year)[T.1987.0]    -0.4289      0.008    -51.438      0.000      -0.445      -0.413
kilometers:C(year)[T.1988.0]    -0.4260      0.008    -51.015      0.000      -0.442      -0.410
kilometers:C(year)[T.1989.0]    -0.4319      0.008    -51.777      0.000      -0.448      -0.416
kilometers:C(year)[T.1990.0]    -0.4293      0.008    -51.357      0.000      -0.446      -0.413
kilometers:C(year)[T.1991.0]    -0.4342      0.008    -52.325      0.000      -0.451      -0.418
kilometers:C(year)[T.1992.0]    -0.4309      0.008    -51.535      0.000      -0.447      -0.415
kilometers:C(year)[T.1993.0]    -0.4343      0.008    -52.019      0.000      -0.451      -0.418
kilometers:C(year)[T.1994.0]    -0.4370      0.008    -52.209      0.000      -0.453      -0.421
kilometers:C(year)[T.1995.0]    -0.4333      0.008    -51.656      0.000      -0.450      -0.417
kilometers:C(year)[T.1996.0]    -0.4308      0.008    -51.929      0.000      -0.447      -0.415
kilometers:C(year)[T.1997.0]    -0.4382      0.008    -52.299      0.000      -0.455      -0.422
kilometers:C(year)[T.1998.0]    -0.4378      0.008    -52.349      0.000      -0.454      -0.421
kilometers:C(year)[T.1999.0]    -0.4389      0.008    -52.047      0.000      -0.455      -0.422
kilometers:C(year)[T.2000.0]    -0.4445      0.009    -51.808      0.000      -0.461      -0.428
kilometers:C(year)[T.2001.0]    -0.4427      0.009    -51.258      0.000      -0.460      -0.426
kilometers:C(year)[T.2002.0]    -0.4425      0.010    -42.495      0.000      -0.463      -0.422
kilometers:C(year)[T.2003.0]    -0.4395      0.009    -49.968      0.000      -0.457      -0.422
kilometers:C(year)[T.2004.0]    -0.4467      0.009    -47.093      0.000      -0.465      -0.428
kilometers:C(year)[T.2005.0]    -0.3958      0.018    -21.790      0.000      -0.431      -0.360
kilometers:C(year)[T.2006.0]    -0.3705      0.046     -7.983      0.000      -0.461      -0.280
==============================================================================
Omnibus:                       95.294   Durbin-Watson:                   1.563
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              771.073
Skew:                          -0.067   Prob(JB):                    3.66e-168
Kurtosis:                       7.711   Cond. No.                     1.19e+16
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC0)
[2] The smallest eigenvalue is 2.61e-19. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [14]:
# Regression with interactions between kilometers and year indicators written differently

results_ols = smf.ols('price_usd ~ kilometers + C(year) + kilometers:C(year)', 
               data=toyota_corolla_df
               ).fit(cov_type='HC0')
print('')
print('Regression with interactions between kilometers and year indicators')
results_ols.summary()

Regression with interactions between kilometers and year indicators

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              price_usd   R-squared:                       0.872
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                 5.599e+15
Date:                Mon, 15 Aug 2022   Prob (F-statistic):               0.00
Time:                        21:14:03   Log-Likelihood:                -7198.2
No. Observations:                 833   AIC:                         1.453e+04
Df Residuals:                     764   BIC:                         1.486e+04
Df Model:                          68
Covariance Type:                  HC0
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                     1586.7928    108.040     14.687      0.000    1375.038    1798.548
C(year)[T.1970.0]            -7.685e-06   1.52e-07    -50.692      0.000   -7.98e-06   -7.39e-06
C(year)[T.1971.0]             5825.9822    108.040     53.924      0.000    5614.227    6037.737
C(year)[T.1972.0]            -4.952e-06   1.48e-07    -33.402      0.000   -5.24e-06   -4.66e-06
C(year)[T.1974.0]             -748.3216    759.792     -0.985      0.325   -2237.487     740.844
C(year)[T.1975.0]            -6.152e-06   8.16e-08    -75.398      0.000   -6.31e-06   -5.99e-06
C(year)[T.1976.0]             8353.8206    108.040     77.321      0.000    8142.066    8565.575
C(year)[T.1977.0]            -2735.3762    108.040    -25.318      0.000   -2947.131   -2523.621
C(year)[T.1978.0]             -476.1269    904.653     -0.526      0.599   -2249.215    1296.961
C(year)[T.1979.0]              541.2391    800.294      0.676      0.499   -1027.308    2109.786
C(year)[T.1980.0]              197.4245    138.412      1.426      0.154     -73.859     468.708
C(year)[T.1981.0]            -8.843e+04    108.040   -818.478      0.000   -8.86e+04   -8.82e+04
C(year)[T.1982.0]            -4.509e-06   3.46e-08   -130.513      0.000   -4.58e-06   -4.44e-06
C(year)[T.1983.0]             3117.4177    204.659     15.232      0.000    2716.294    3518.542
C(year)[T.1984.0]             -511.0931   1282.828     -0.398      0.690   -3025.390    2003.203
C(year)[T.1985.0]               65.4216    499.189      0.131      0.896    -912.971    1043.814
C(year)[T.1986.0]             1614.3273   1177.500      1.371      0.170    -693.531    3922.186
C(year)[T.1987.0]              220.7327    472.560      0.467      0.640    -705.467    1146.933
C(year)[T.1988.0]             -918.5330    409.087     -2.245      0.025   -1720.330    -116.736
C(year)[T.1989.0]             1062.8597    434.811      2.444      0.015     210.646    1915.073
C(year)[T.1990.0]              -11.3606    352.931     -0.032      0.974    -703.092     680.371
C(year)[T.1991.0]             1598.2903    591.489      2.702      0.007     438.992    2757.588
C(year)[T.1992.0]              544.6490    367.340      1.483      0.138    -175.325    1264.622
C(year)[T.1993.0]             2058.4739    480.473      4.284      0.000    1116.763    3000.184
C(year)[T.1994.0]             2552.5543    409.971      6.226      0.000    1749.025    3356.083
C(year)[T.1995.0]             1947.4925    474.069      4.108      0.000    1018.334    2876.651
C(year)[T.1996.0]             1439.5151    904.150      1.592      0.111    -332.586    3211.616
C(year)[T.1997.0]             3481.4458    455.894      7.637      0.000    2587.911    4374.981
C(year)[T.1998.0]             3952.9141    603.591      6.549      0.000    2769.897    5135.931
C(year)[T.1999.0]             4383.7075    737.223      5.946      0.000    2938.777    5828.638
C(year)[T.2000.0]             5035.1410    732.444      6.874      0.000    3599.578    6470.704
C(year)[T.2001.0]             5871.3088    527.675     11.127      0.000    4837.085    6905.532
C(year)[T.2002.0]             6435.0136    928.559      6.930      0.000    4615.071    8254.956
C(year)[T.2003.0]             8341.9780    440.962     18.918      0.000    7477.708    9206.248
C(year)[T.2004.0]             9055.8543    561.013     16.142      0.000    7956.290    1.02e+04
C(year)[T.2005.0]             7951.6475    654.786     12.144      0.000    6668.291    9235.004
C(year)[T.2006.0]             9766.8757    726.966     13.435      0.000    8342.048    1.12e+04
kilometers                       0.4263      0.008     50.798      0.000       0.410       0.443
kilometers:C(year)[T.1970.0]    -0.3847      0.006    -60.454      0.000      -0.397      -0.372
kilometers:C(year)[T.1971.0]    -0.4748      0.008    -56.587      0.000      -0.491      -0.458
kilometers:C(year)[T.1972.0]    -0.4050      0.006    -63.115      0.000      -0.418      -0.392
kilometers:C(year)[T.1974.0]    -0.4200      0.008    -50.725      0.000      -0.436      -0.404
kilometers:C(year)[T.1975.0]    -0.4165      0.007    -57.120      0.000      -0.431      -0.402
kilometers:C(year)[T.1976.0]    -0.4613      0.008    -54.967      0.000      -0.478      -0.445
kilometers:C(year)[T.1977.0]    -0.4171      0.008    -49.711      0.000      -0.434      -0.401
kilometers:C(year)[T.1978.0]    -0.4199      0.009    -44.468      0.000      -0.438      -0.401
kilometers:C(year)[T.1979.0]    -0.4314      0.009    -50.055      0.000      -0.448      -0.414
kilometers:C(year)[T.1980.0]    -0.4288      0.008    -51.116      0.000      -0.445      -0.412
kilometers:C(year)[T.1981.0]     0.3003      0.008     35.786      0.000       0.284       0.317
kilometers:C(year)[T.1982.0]    -0.4283      0.008    -52.432      0.000      -0.444      -0.412
kilometers:C(year)[T.1983.0]    -0.4407      0.008    -51.955      0.000      -0.457      -0.424
kilometers:C(year)[T.1984.0]    -0.4241      0.008    -50.714      0.000      -0.440      -0.408
kilometers:C(year)[T.1985.0]    -0.4238      0.008    -50.362      0.000      -0.440      -0.407
kilometers:C(year)[T.1986.0]    -0.4309      0.008    -53.995      0.000      -0.446      -0.415
kilometers:C(year)[T.1987.0]    -0.4289      0.008    -51.438      0.000      -0.445      -0.413
kilometers:C(year)[T.1988.0]    -0.4260      0.008    -51.015      0.000      -0.442      -0.410
kilometers:C(year)[T.1989.0]    -0.4319      0.008    -51.777      0.000      -0.448      -0.416
kilometers:C(year)[T.1990.0]    -0.4293      0.008    -51.357      0.000      -0.446      -0.413
kilometers:C(year)[T.1991.0]    -0.4342      0.008    -52.325      0.000      -0.451      -0.418
kilometers:C(year)[T.1992.0]    -0.4309      0.008    -51.535      0.000      -0.447      -0.415
kilometers:C(year)[T.1993.0]    -0.4343      0.008    -52.019      0.000      -0.451      -0.418
kilometers:C(year)[T.1994.0]    -0.4370      0.008    -52.209      0.000      -0.453      -0.421
kilometers:C(year)[T.1995.0]    -0.4333      0.008    -51.656      0.000      -0.450      -0.417
kilometers:C(year)[T.1996.0]    -0.4308      0.008    -51.929      0.000      -0.447      -0.415
kilometers:C(year)[T.1997.0]    -0.4382      0.008    -52.299      0.000      -0.455      -0.422
kilometers:C(year)[T.1998.0]    -0.4378      0.008    -52.349      0.000      -0.454      -0.421
kilometers:C(year)[T.1999.0]    -0.4389      0.008    -52.047      0.000      -0.455      -0.422
kilometers:C(year)[T.2000.0]    -0.4445      0.009    -51.808      0.000      -0.461      -0.428
kilometers:C(year)[T.2001.0]    -0.4427      0.009    -51.258      0.000      -0.460      -0.426
kilometers:C(year)[T.2002.0]    -0.4425      0.010    -42.495      0.000      -0.463      -0.422
kilometers:C(year)[T.2003.0]    -0.4395      0.009    -49.968      0.000      -0.457      -0.422
kilometers:C(year)[T.2004.0]    -0.4467      0.009    -47.093      0.000      -0.465      -0.428
kilometers:C(year)[T.2005.0]    -0.3958      0.018    -21.790      0.000      -0.431      -0.360
kilometers:C(year)[T.2006.0]    -0.3705      0.046     -7.983      0.000      -0.461      -0.280
==============================================================================
Omnibus:                       95.294   Durbin-Watson:                   1.563
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              771.073
Skew:                          -0.067   Prob(JB):                    3.66e-168
Kurtosis:                       7.711   Cond. No.                     1.19e+16
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC0)
[2] The smallest eigenvalue is 2.61e-19. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [18]:
toyota_corolla_with_a_bid_df = pd.read_csv(
    'https://firebasestorage.googleapis.com/v0/b/acst001.appspot.com/o/Dataset_eBay_Toyota_Corolla_with_a_bid_v001.csv?alt=media&token=de1ce403-3e2d-40f0-bd3e-21094da3c7da'
    )

In [19]:
toyota_corolla_with_a_bid_df

,record_id,sell,price_usd,kilometers,miles,year,maker,model
0,21,0,7600.00,89257,55462.0,2003.0,Toyota,Corolla
1,63,0,10300.00,15772,9800.0,2005.0,Toyota,Corolla
2,65,0,9095.00,15772,9800.0,2005.0,Toyota,Corolla
3,245,0,10000.00,61155,38000.0,2004.0,Toyota,Corolla
4,627,0,3170.00,183465,114000.0,1980.0,Toyota,Corolla
...,...,...,...,...,...,...,...,...
1624,145828,0,10000.00,63793,39639.0,2005.0,Toyota,Corolla
1625,146015,1,1525.00,332007,206300.0,1994.0,Toyota,Corolla
1626,146132,1,536.09,144841,90000.0,1978.0,Toyota,Corolla
1627,146385,1,4299.00,106469,66157.0,2001.0,Toyota,Corolla
1628,146673,1,560.00,257495,160000.0,1995.0,Toyota,Corolla

In [36]:
results_logit = smf.logit('sell ~ kilometers + year', 
               data=toyota_corolla_with_a_bid_df
               ).fit()
print('')
print('Logit regression of the indicator of a successful sale.')
results_logit.summary()

Optimization terminated successfully.
         Current function value: 0.632219
         Iterations 5

Logit regression of the indicator of a successful sale.

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                   sell   No. Observations:                 1629
Model:                          Logit   Df Residuals:                     1626
Method:                           MLE   Df Model:                            2
Date:                Mon, 15 Aug 2022   Pseudo R-squ.:                 0.08756
Time:                        21:30:50   Log-Likelihood:                -1029.9
converged:                       True   LL-Null:                       -1128.7
Covariance Type:            nonrobust   LLR p-value:                 1.197e-43
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     73.5957     18.152      4.055      0.000      38.019     109.172
kilometers  5.229e-06   6.77e-07      7.729      0.000     3.9e-06    6.55e-06
year          -0.0372      0.009     -4.103      0.000      -0.055      -0.019
==============================================================================
"""

In [29]:
results_logit = smf.logit('sell ~ price_usd + kilometers + year', 
               data=toyota_corolla_with_a_bid_df
               ).fit()
print('')
print('Logit regression of the indicator of a successful sale.')
results_logit.summary()

Optimization terminated successfully.
         Current function value: 0.632119
         Iterations 6

Logit regression of the indicator of a successful sale.

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                   sell   No. Observations:                 1629
Model:                          Logit   Df Residuals:                     1625
Method:                           MLE   Df Model:                            3
Date:                Mon, 15 Aug 2022   Pseudo R-squ.:                 0.08771
Time:                        21:21:57   Log-Likelihood:                -1029.7
converged:                       True   LL-Null:                       -1128.7
Covariance Type:            nonrobust   LLR p-value:                 1.146e-42
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     66.5223     21.882      3.040      0.002      23.634     109.410
price_usd  -1.449e-05   2.53e-05     -0.573      0.567    -6.4e-05    3.51e-05
kilometers  4.927e-06   8.54e-07      5.766      0.000    3.25e-06     6.6e-06
year          -0.0336      0.011     -3.055      0.002      -0.055      -0.012
==============================================================================
"""

In [31]:
results_logit = smf.logit('sell ~ price_usd + kilometers + C(year)', 
               data=toyota_corolla_with_a_bid_df
               ).fit()
print('')
print('Logit regression of the indicator of a successful sale.')
results_logit.summary()

Logit regression of the indicator of a successful sale.

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                   sell   No. Observations:                 1629
Model:                          Logit   Df Residuals:                     1589
Method:                           MLE   Df Model:                           39
Date:                Mon, 15 Aug 2022   Pseudo R-squ.:                  0.1372
Time:                        21:23:56   Log-Likelihood:                -973.82
converged:                      False   LL-Null:                       -1128.7
Covariance Type:            nonrobust   LLR p-value:                 7.168e-44
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            14.0296   1628.575      0.009      0.993   -3177.920    3205.979
C(year)[T.1970.0]    13.5058   1.26e+06   1.07e-05      1.000   -2.47e+06    2.47e+06
C(year)[T.1971.0]   -14.6100   1628.576     -0.009      0.993   -3206.560    3177.340
C(year)[T.1972.0]   -14.4415   1628.576     -0.009      0.993   -3206.392    3177.509
C(year)[T.1974.0]   -14.4897   1628.576     -0.009      0.993   -3206.439    3177.460
C(year)[T.1975.0]   -14.4486   1628.576     -0.009      0.993   -3206.399    3177.502
C(year)[T.1976.0]   -14.7883   1628.576     -0.009      0.993   -3206.738    3177.162
C(year)[T.1977.0]   -15.0789   1628.576     -0.009      0.993   -3207.029    3176.871
C(year)[T.1978.0]   -14.0303   1628.576     -0.009      0.993   -3205.980    3177.919
C(year)[T.1979.0]   -14.3363   1628.576     -0.009      0.993   -3206.286    3177.613
C(year)[T.1980.0]   -14.7978   1628.576     -0.009      0.993   -3206.747    3177.152
C(year)[T.1981.0]   -15.3944   1628.576     -0.009      0.992   -3207.344    3176.555
C(year)[T.1982.0]   -17.1348   1628.576     -0.011      0.992   -3209.085    3174.815
C(year)[T.1983.0]   -14.8758   1628.576     -0.009      0.993   -3206.825    3177.074
C(year)[T.1984.0]   -14.2276   1628.576     -0.009      0.993   -3206.177    3177.722
C(year)[T.1985.0]   -13.7993   1628.575     -0.008      0.993   -3205.749    3178.150
C(year)[T.1986.0]   -14.0616   1628.576     -0.009      0.993   -3206.011    3177.888
C(year)[T.1987.0]   -14.0397   1628.575     -0.009      0.993   -3205.989    3177.910
C(year)[T.1988.0]   -14.5229   1628.576     -0.009      0.993   -3206.472    3177.426
C(year)[T.1989.0]   -14.2693   1628.575     -0.009      0.993   -3206.219    3177.680
C(year)[T.1990.0]   -13.2676   1628.576     -0.008      0.993   -3205.217    3178.682
C(year)[T.1991.0]   -13.5101   1628.575     -0.008      0.993   -3205.459    3178.439
C(year)[T.1992.0]   -13.5278   1628.575     -0.008      0.993   -3205.477    3178.421
C(year)[T.1993.0]   -12.3342   1628.576     -0.008      0.994   -3204.284    3179.615
C(year)[T.1994.0]   -13.9406   1628.575     -0.009      0.993   -3205.890    3178.009
C(year)[T.1995.0]   -13.7544   1628.575     -0.008      0.993   -3205.704    3178.195
C(year)[T.1996.0]   -14.4277   1628.575     -0.009      0.993   -3206.377    3177.522
C(year)[T.1997.0]   -13.4590   1628.575     -0.008      0.993   -3205.408    3178.490
C(year)[T.1998.0]   -15.3556   1628.575     -0.009      0.992   -3207.305    3176.594
C(year)[T.1999.0]   -14.7604   1628.575     -0.009      0.993   -3206.710    3177.189
C(year)[T.2000.0]   -14.8385   1628.575     -0.009      0.993   -3206.788    3177.111
C(year)[T.2001.0]   -15.1112   1628.575     -0.009      0.993   -3207.060    3176.838
C(year)[T.2002.0]   -15.4740   1628.575     -0.010      0.992   -3207.423    3176.475
C(year)[T.2003.0]   -15.6482   1628.575     -0.010      0.992   -3207.597    3176.301
C(year)[T.2004.0]   -15.7676   1628.575     -0.010      0.992   -3207.717    3176.182
C(year)[T.2005.0]   -16.2374   1628.575     -0.010      0.992   -3208.187    3175.712
C(year)[T.2006.0]   -15.9789   1628.575     -0.010      0.992   -3207.928    3175.970
C(year)[T.2007.0]   -29.1542   2088.629     -0.014      0.989   -4122.792    4064.483
price_usd             0.0001   3.49e-05      2.913      0.004    3.33e-05       0.000
kilometers         3.293e-06   9.65e-07      3.412      0.001     1.4e-06    5.18e-06
=====================================================================================
"""